### PR TITLE
Added Hash and Eq to the categories.

### PR DESCRIPTION
**Pull request by MGlolenstine**

### CODE REVIEW

**Comment by MGlolenstine** [comment]
I'm planning on updating reqwest version in following days, but it's currently evading me.

**Comment by baptistecdr** [comment]
Thanks, I updated the dependencies 👍

**Comment by MGlolenstine** [comment]
You're welcome!
Currently the reqwest `0.11.0` uses tokio `1.2.0`, which is what we want to use to comply with the tokio version we use, but it changed how runtimes work and it crashes during the runtime.


<details>
<summary>This is the stacktrace if it helps.</summary>

```
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\blocking\shutdown.rs:51:21
stack backtrace:
   0: std::panicking::begin_panic<str*>
             at C:\Users\LifEorDeatH\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:505
   1: tokio::runtime::blocking::shutdown::Receiver::wait
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\blocking\shutdown.rs:51        
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\blocking\pool.rs:158
   3: tokio::runtime::blocking::pool::{{impl}}::drop
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.2.0\src\runtime\blocking\pool.rs:175
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at C:\Users\LifEorDeatH\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:184 
   5: core::ptr::drop_in_place<tokio::runtime::Runtime>
             at C:\Users\LifEorDeatH\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:184
   6: reqwest::blocking::wait::enter
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.11.0\src\blocking\wait.rs:73
   7: reqwest::blocking::wait::timeout<tokio::sync::oneshot::Receiver<core::result::Result<tuple<>, reqwest::error::Error>>,core::result::Result<tuple<>, reqwest::error::Error>,tokio::sync::oneshot::error::RecvError>
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.11.0\src\blocking\wait.rs:14
   8: reqwest::blocking::client::ClientHandle::new
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.11.0\src\blocking\client.rs:787
   9: reqwest::blocking::client::ClientBuilder::build
             at C:\Users\LifEorDeatH\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.11.0\src\blocking\client.rs:96
  10: rarbg_api::token::Token::get
             at C:\Users\LifEorDeatH\Desktop\projects\rarbg_api\src\token.rs:70
  11: rarbg_api::token::Token::new
             at C:\Users\LifEorDeatH\Desktop\projects\rarbg_api\src\token.rs:57
  12: rarbg_api::RarBgApi::new
             at C:\Users\LifEorDeatH\Desktop\projects\rarbg_api\src\lib.rs:85
```
</details>

I'll work on it later today.

**Comment by baptistecdr** [comment]
Maybe you see it but maybe this is what your are looking for ? https://github.com/seanmonstar/reqwest/issues/1017#issuecomment-773719586

**Comment by MGlolenstine** [comment]
I haven't seen this yet, but you might be right!
This might be a solution.

[This](https://github.com/baptistecdr/rarbg_api/blob/master/src/token.rs#L70-L75) is all blocking, but none of it is awaiting.
I'll check it out when I get off work.

**Comment by baptistecdr** [comment]
In the last commit, I converted the code from Rust 2015 to Rust 2018 with support of async/await.
Example:
```rust
extern crate rarbg_api;

use rarbg_api::api_parameters_builder::ApiParametersBuilder;
use rarbg_api::category::Category;
use rarbg_api::limit::Limit;
use rarbg_api::RarBgApi;
use rarbg_api::sort_by::SortBy;

#[tokio::main]
pub async fn main() -> Result<(), ()> {
    let mut api = RarBgApi::new("my_app_id").await;
    let parameters = ApiParametersBuilder::new()
        .limit(Limit::TwentyFive)
        .categories(vec![Category::TvUhdEpisodes, Category::TvHdEpisodes, Category::TvEpisodes])
        .sort_by(SortBy::Seeders)
        .build();
    let result = api.search("Rick and Morty", Some(&parameters)).await;
    match result {
        // Export first torrent found in the current directory.
        // The file contains a magnet link that can be added in your Bittorrent client.
        Ok(result) => result.torrents().iter().take(1).for_each(|t| println!("Torrent exported to '{}'.", t.export(".").unwrap())),
        Err(reason) => println!("{}", reason.error())
    }
    Ok(())
}
```

Is this fix your error now that this is non-blocking ?

**Comment by MGlolenstine** [comment]
You were correct, that did indeed fix my problem.
Thanks!

**Pull request merged**
